services:
  frontend:
    ports: !override
      - "80:80"
      - "443:443"
      - "8090:443"
    volumes:
      - ./frontend/nginx.https.conf:/etc/nginx/conf.d/neo4flix.conf:ro
      - ./certs:/etc/nginx/certs:ro
