server:
  port: 8081

spring:
  application:
    name: movie-service

  # Connexion Neo4j (Bolt)
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: ${NEO4J_PASSWORD:neo4flix123}

  data:
    neo4j:
      database: neo4j

# Endpoints actuator pour healthcheck
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: when_authorized

# Doc Swagger UI : http://localhost:8081/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.data.neo4j: INFO
